// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHG3TjPr5OGBthwdq-YXATx2aq6Z-zYiY',
    appId: '1:366271370685:web:ea48137e00606a86106ed4',
    messagingSenderId: '366271370685',
    projectId: 'chat-15eba',
    authDomain: 'chat-15eba.firebaseapp.com',
    storageBucket: 'chat-15eba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtAZUIkTij2AnGRRBa8w8ETHf8DM0mE4',
    appId: '1:366271370685:android:5623f6d537930a5d106ed4',
    messagingSenderId: '366271370685',
    projectId: 'chat-15eba',
    storageBucket: 'chat-15eba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKA7RGsTYQvX9PriIyEz91y6nsUgrj4yg',
    appId: '1:366271370685:ios:f67ded4d102ea1aa106ed4',
    messagingSenderId: '366271370685',
    projectId: 'chat-15eba',
    storageBucket: 'chat-15eba.firebasestorage.app',
    iosBundleId: 'com.chat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKA7RGsTYQvX9PriIyEz91y6nsUgrj4yg',
    appId: '1:366271370685:ios:1e9f02c9fa9844a8106ed4',
    messagingSenderId: '366271370685',
    projectId: 'chat-15eba',
    storageBucket: 'chat-15eba.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHG3TjPr5OGBthwdq-YXATx2aq6Z-zYiY',
    appId: '1:366271370685:web:482258d8edadb975106ed4',
    messagingSenderId: '366271370685',
    projectId: 'chat-15eba',
    authDomain: 'chat-15eba.firebaseapp.com',
    storageBucket: 'chat-15eba.firebasestorage.app',
  );
}
